Map<String, String> enUS = {
  "resumebuilder": "Resume Builder",
  "preview": "Preview",
  "resume": "Resume",
  "aboutme": "ABOUT ME",
  "contactinfo": "CONTACT INFO",
  "languages": "LANGUAGES",
  "achievemenets": "ACHIEVEMENTS",
  "intarests": "INTARESTS",
  "objective": "OBJECTIVE",
  "workexp": "WORK EXPERIENCE",
  "education": "EDUCATION",
  "project": "PROJECT",
  "addresume": "Add Resume",
  "entername": "Enter your Name",
  "name": "Name",
  "enterlinkedinurl": "Enter your linkedin url",
  "linkedin": "Linkedin",
  "entergithuburl": "Enter your Github url",
  "github": "Github",
  "number": "Number",
  "email": "Email",
  "city": "city,state",
  "address": "Address",
  "hindi": "Hindi,English,Gujarati",
  "sanguages": "Languages",
  "achievements": "Achievements",
  "interests": "Interests",
  "sports": "Singing,Playing sports",
  "objectives": "Objective",
  "workexperience": "Work Experience",
  "educations": "Education",
  "projects": "Project",
  "addworkexeprience": "Add Work Exeprience",
  "xyztech": "xyz Tech.",
  "companyname": "Company name",
  "flutterdevloper": "Flutter Devloper",
  "job": "Job",
  "description": "Description",
  "joiningdate": "Joining date",
  "save": "Save",
  "addeducation": "Add Education",
  "xyzschool": "xyz School",
  "scname": "School/College Name",
  "commerce": "Commerce",
  "course": "Course",
  "percentage": "Percentage",
  "addproject": "Add Project",
  "projectname": "Project Name",
  "aboutproject": "About Project",
  "about": "About",
  "add": "Add",
  "resumeisempty": 'Resume is Empty'
};
